### ISSUE TITLE
Any reason why using my own storage causes cluster to fail "not ready"

### ISSUE THREAD

**Issue by bodleytunes** [schu/kubedee#23]
Hi

I've gave a whole disk to lxd manually and called the storage "kubedee".   I then follow normal procedure to create a cluster and it all looks to work, goes through the motions without error.

However, it stays stuck in "not ready" mode for all nodes and I notice flannel doesn't get deployed properly as the interfaces don't appear thus there is no resulting CNI.

If I delete the cluster and delete the custom storage then try with kubeedee and let it create its own storage, it works fine.

Seems strange as the storage I create is just a bigger pool and using an entire drive as the "source=/dev/sdb", but using BTRFS as the filesystem.

Any ideas?

Cheers!
Jon :)

**Comment by schu** [comment]
Hi. Hmm, do you see something in `journalctl -u kubelet`?

**Comment by schu** [comment]
Closing, please reopen if still an issue.
